theme: jekyll-theme-minimal
title: "crypt[dot]fi"
description: "Co-owner of TheManyHatsClub"
baseurl: ""
url: "https://crypt.fi"
twitter_username: buydogs
collections:
  posts:
    title: Posts
    output: true
permalink: "/blog/:title"
