theme: jekyll-theme-dinky
title: "crypt[dot]fi"
description: "
Welcome to crypt.fi, a site focused on Privacy and OSINT. 
Here you'll find material written by guest writers and I.
Check the Homepage for more details."
baseurl: ""
url: "https://crypt.fi"
twitter_username: buydogs
layout: splash
classes:
  - landing
  - dark-theme
collections:
  posts:
    title: Posts
    output: true
permalink: "/blog/:title"

