theme: jekyll-theme-dinky
title: "crypt[dot]fi"
description: "

Welcome to crypt.fi, a site ran by Dave. 
Here you'll find Privacy and OSINT focused material written by me and other guest writers.
Check the Homepage for more details."
baseurl: ""
url: "https://crypt.fi"
twitter_username: buydogs
layout: splash
classes:
  - landing
  - dark-theme
collections:
  posts:
    title: Posts
    output: true
permalink: "/blog/:title"
